# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "2181" # Zookeeper
  - "5044" # Logstash
  - "5601" # Kibana
  - "9092" # Kafka
  - "9200" # Elasticsearch
  - "9300" # Elasticsearch



es_ip: "127.0.0.1"
kafka_ip: "127.0.0.1"
logstash_ip: "127.0.0.1"
kibana_ip: "127.0.0.1"



# apolloclark/crontab
crontab:
  global:
    - "@reboot root /home/vagrant/restart_elk_services.sh"

# apolloclark/kibana
kibana:
  version: "7.3.0"
